import React from 'react';

const LANG_NAMES = {
  hi:'Hindi', ta:'Tamil', te:'Telugu', bn:'Bengali', mr:'Marathi',
  gu:'Gujarati', kn:'Kannada', ml:'Malayalam', pa:'Punjabi', or:'Odia',
  fr:'French', es:'Spanish', ar:'Arabic', en:'English'
};

export default function AnalyticsPage({ stats, articles }) {
  const langCount = {};
  (articles || []).forEach(a => {
    (a.translations || []).forEach(t => {
      langCount[t.language_code] = (langCount[t.language_code] || 0) + 1;
    });
  });
  const sortedLangs = Object.entries(langCount).sort((a, b) => b[1] - a[1]);
  const maxLang = sortedLangs[0]?.[1] || 1;

  const categories = {};
  (articles || []).forEach(a => {
    categories[a.category] = (categories[a.category] || 0) + 1;
  });
  const sortedCats = Object.entries(categories).sort((a, b) => b[1] - a[1]);
  const maxCat = sortedCats[0]?.[1] || 1;

  const sensitivityCounts = { safe: 0, low: 0, medium: 0, high: 0, critical: 0 };
  (articles || []).forEach(a => {
    if (a.sensitivity?.overall_level) {
      sensitivityCounts[a.sensitivity.overall_level] = (sensitivityCounts[a.sensitivity.overall_level] || 0) + 1;
    }
  });

  const total = stats?.total || 0;
  const publishRate = total > 0 ? Math.round(((stats?.published || 0) / total) * 100) : 0;
  const avgTranslations = total > 0 ? ((stats?.total_translations || 0) / total).toFixed(1) : 0;

  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <h1 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Analytics</h1>
        <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>Pipeline performance and content distribution insights</p>
      </div>

      {/* KPI Row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 20 }}>
        {[
          { label: 'Publish Rate', value: `${publishRate}%`, sub: 'of ingested articles', color: 'var(--green)' },
          { label: 'Avg. Languages', value: avgTranslations, sub: 'per article', color: 'var(--cyan)' },
          { label: 'Total Translations', value: stats?.total_translations || 0, sub: 'generated by AI', color: 'var(--purple)' },
          { label: 'Critical Flags', value: stats?.critical_flags || 0, sub: 'require attention', color: 'var(--red)' },
        ].map(k => (
          <div key={k.label} className="card" style={{ textAlign: 'center' }}>
            <div style={{ fontSize: 32, fontWeight: 700, color: k.color }}>{k.value}</div>
            <div style={{ fontSize: 13, fontWeight: 600, margin: '4px 0 2px' }}>{k.label}</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{k.sub}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
        {/* Language Distribution */}
        <div className="card">
          <div className="card-title" style={{ marginBottom: 16 }}>Translation by Language</div>
          {sortedLangs.length === 0 ? (
            <div className="empty-state" style={{ padding: 20 }}>No translation data yet.</div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {sortedLangs.map(([code, count]) => (
                <div key={code}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                    <span style={{ color: 'var(--text-secondary)' }}>{LANG_NAMES[code] || code}</span>
                    <span style={{ fontWeight: 600 }}>{count}</span>
                  </div>
                  <div style={{ height: 6, background: 'var(--border)', borderRadius: 3 }}>
                    <div style={{ height: '100%', width: `${(count / maxLang) * 100}%`, background: 'linear-gradient(90deg, var(--blue), var(--cyan))', borderRadius: 3, transition: 'width 0.5s ease' }} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Category Distribution */}
        <div className="card">
          <div className="card-title" style={{ marginBottom: 16 }}>Articles by Category</div>
          {sortedCats.length === 0 ? (
            <div className="empty-state" style={{ padding: 20 }}>No category data yet.</div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {sortedCats.map(([cat, count]) => (
                <div key={cat}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                    <span style={{ color: 'var(--text-secondary)' }}>{cat}</span>
                    <span style={{ fontWeight: 600 }}>{count}</span>
                  </div>
                  <div style={{ height: 6, background: 'var(--border)', borderRadius: 3 }}>
                    <div style={{ height: '100%', width: `${(count / maxCat) * 100}%`, background: 'linear-gradient(90deg, var(--purple), var(--pink))', borderRadius: 3 }} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        {/* Sensitivity Distribution */}
        <div className="card">
          <div className="card-title" style={{ marginBottom: 16 }}>Content Sensitivity Distribution</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {Object.entries(sensitivityCounts).map(([level, count]) => {
              const colors = { safe: 'var(--green)', low: '#84cc16', medium: 'var(--yellow)', high: 'var(--orange)', critical: 'var(--red)' };
              const total = Object.values(sensitivityCounts).reduce((a, b) => a + b, 0) || 1;
              return (
                <div key={level} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <span className={`badge severity-${level}`} style={{ minWidth: 70 }}>{level}</span>
                  <div style={{ flex: 1, height: 8, background: 'var(--border)', borderRadius: 4 }}>
                    <div style={{ height: '100%', width: `${(count / total) * 100}%`, background: colors[level], borderRadius: 4 }} />
                  </div>
                  <span style={{ fontSize: 12, fontWeight: 600, minWidth: 20 }}>{count}</span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Article Status Funnel */}
        <div className="card">
          <div className="card-title" style={{ marginBottom: 16 }}>Pipeline Funnel</div>
          {[
            { label: 'Ingested', key: 'total', color: 'var(--blue)' },
            { label: 'Processed', key: 'review', color: 'var(--purple)' },
            { label: 'Approved', key: 'approved', color: 'var(--green)' },
            { label: 'Published', key: 'published', color: 'var(--cyan)' },
          ].map(s => {
            const val = stats?.[s.key] || 0;
            const pct = total > 0 ? Math.round((val / total) * 100) : 0;
            return (
              <div key={s.key} style={{ marginBottom: 12 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 4 }}>
                  <span style={{ color: 'var(--text-secondary)' }}>{s.label}</span>
                  <span style={{ fontWeight: 600 }}>{val} <span style={{ color: 'var(--text-muted)', fontWeight: 400 }}>({pct}%)</span></span>
                </div>
                <div style={{ height: 8, background: 'var(--border)', borderRadius: 4 }}>
                  <div style={{ height: '100%', width: `${pct}%`, background: s.color, borderRadius: 4, transition: 'width 0.5s ease' }} />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
